version: '3'

services:
  image-process:
    build:
      context: .
      dockerfile: ./Dockerfile-dev

    ports:
      - '50051:50051'
    # command:
    #   - python serve.py
    tty: true
    volumes:
      - ../:/refri_be/
