service: refri-be-lambda
frameworkVersion: '3'

provider:
  name: aws
  region: ap-northeast-2
  runtime: nodejs18.x
  memorySize: 10240
  timeout: 3
  logs:
    restApi: true
  environment:
    DEV_HOST: ${env:DEV_HOST}
    DEV_STAGE: ${env:DEV_STAGE}
    DATABASE_URI: ${env:DATABASE_URI}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRES_IN: ${env:JWT_EXPIRES_IN}
    JWT_REFRESH_EXPIRES_IN: ${env:JWT_REFRESH_EXPIRES_IN}

package:
  individually: true

useDotenv: true

functions:
  mono_lambda:
    handler: dist/apps/mono_lambda/main.handler
    package:
      patterns:
        - '!**/*'
        - dist/apps/mono_lambda/main.js
    events:
      - http:
          path: '/'
          method: any
          cors: true
      - http:
          path: '{proxy+}'
          method: any
          cors: true
